
### GET ALL CATEGORIE PERMISSIONS
GET http://localhost:8000/api/categorie_permissions

### ADD NEW CATEGORIE PERMISSION
POST http://localhost:8000/api/categorie_permissions
Content-Type: application/json

{
    "categorie_permission_name":"utilisateurs"
}
### UPDATE EXISTING CATEGORIE PERMISSION
PUT http://localhost:8000/api/categorie_permissions/1
Content-Type: application/json

{
    "categorie_permission_name":"serveurs"
}
### DELETE EXISTING CATEGORIE PERMISSION
DELETE http://localhost:8000/api/categorie_permissions/1

