
### GET ALL USER
GET http://localhost:8000/api/users

### GET ALL ROLES
GET http://localhost:8000/api/roles
Content-Type: application/json
Authorization: Bearer 6|5NN4aZRTHwfJkO90ILD5yjmQL393M3NSAMtU1eFt
### ADD NEW USER
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "name":"Duro",
    "email":"Duro@Jaiye.com",
    "password":"123456789"
}
### Another Action

### GET ALL USER
GET http://localhost:8000/api/me
Authorization: Bearer 49|OnMuowZyIbziNM50N2DVL1C4ybgg9MrLcyXlVzv3

### GET PERMISSION
GET http://localhost:8000/api/get-permissions
Authorization: Bearer 22|DBIZqPQboIQxPsycolXIcOdMtWPKqv06tNDIXMd2